### PR TITLE
Set printWidth to 120, we're not in the 80ies anymore

### PR DESCRIPTION
**Pull request by Primajin**

### CODE REVIEW

**Review by tschaub — APPROVED** [review]

**Comment by Jiert** [comment]
FWIW, I'm not in favor of this change. It's subjective.

**Comment by tschaub** [comment]
> FWIW, I'm not in favor of this change. Since this is a subjective change, we should probably get everyone's opinion before we merge this.

Sounds good.  I also think it makes sense to avoid a lot of churn due to purely subjective changes.

Maybe it is worth making sure we all agree on the primary objectives of a shared config:

 * make it easier for people to work on multiple projects by having consistent style/formatting
 * catch things that might be bugs

Are there other top level objectives?

**Comment by Jiert** [comment]
I agree on the primary objectives. So the question is: which teams intend on using this config? The US based apps team has been using this config for all of its projects. @Primajin is the Berlin team using or considering using this for all of their projects as well? If so, we should democratically decide what features we want to enforce. As far as I'm aware, the only code base that has been worked on by both teams recently in the GraphQL server. If that's true, this seems like a lot of churn for one shared code base.

**Comment by Primajin** [comment]
Yes we use and have used the config in all of our projects, however always extended it as it didn't fit entirely for us in the past and as of now.

**Comment by tschaub** [comment]
> however always extended it as it didn't fit entirely for us in the past and as of now.

Is there another objective in addition to the two above that you think we should be working towards (I know those are pretty broad and leave lots of room for interpretation)?

**Comment by Primajin** [comment]
I would say we should also work towards minimizing merge conflicts and maximizing consistency.

That's why I'm in favor for enforcing sorting (coming in a later PR also for objects) on many things, because then we all agree on one way to sort things (alphabet) instead of sort things as whoever wants. Furthermore when you look at a longer list of "things" you know exactly *where* you need to scroll to / look for

Screenshot 2020-11-10 at 09 40 12

In this longer object of constants - let's say I'm searching for END_TIME I can directly scroll down to the character E because I know the object is sorted.

Regarding the length of code prettier - yes they suggest shorter but they also say
> Prettier’s printWidth option does not work the same way. It is not the hard upper allowed line length limit. It is a way to say to Prettier roughly how long you’d like lines to be. Prettier will make both shorter and longer lines, but generally strive to meet the specified printWidth.

If we want to compromise we can gradually increase but that would mean if we like it we need to do things twice.

I find it often very unnecessary for short objects or elements to break into multiple lines when they have just two or three properties.
Especially when having multiple objects for example in props of JSX I find this

```jsx
    <MuiThemeProvider theme={theme}>
      <CssBaseline />
      <Grid className={global} container wrap="nowrap">
        <GlobalError />
        <GlobalSuccess />
        <Grid className={container}>
          <Suspense fallback={<CircularProgress className={spinner} color="inherit" size={16} />}>
            <PageSkeleton>
              <MuiPickersUtilsProvider utils={MomentUtils}>
                <ErrorBoundary>
                  <Switch>
                    <Route exact path="/:url*" render={redirectToTrailingSlash} strict />
                    <Route component={Login} path={PATH_LOGIN} />
                    <Route component={Logout} path={PATH_LOGOUT} />
                    <Redirect exact from={PATH_ORDER_ENTRY} key={PATH_ORDER_ENTRY} to={PATH_ORDERS} />
                    <Redirect exact from={PATH_ORDER_ENTRY_ALT} key={PATH_ORDER_ENTRY_ALT} to={PATH_ORDERS} />
                    <AuthRoute component={Order} isLoggedIn={isLoggedIn} path={PATH_ORDER_ID} />
                    <AuthRoute component={Order} isLoggedIn={isLoggedIn} path={PATH_ORDER_ID_ALT} />
```

way more structured and readable than

```jsx
    <MuiThemeProvider theme={theme}>
      <CssBaseline />
      <Grid className={global} container wrap="nowrap">
        <GlobalError />
        <GlobalSuccess />
        <Grid className={container}>
          <Suspense
            fallback={
              <CircularProgress className={spinner} color="inherit" size={16} />
            }
          >
            <PageSkeleton>
              <MuiPickersUtilsProvider utils={MomentUtils}>
                <ErrorBoundary>
                  <Switch>
                    <Route
                      exact
                      path="/:url*"
                      render={redirectToTrailingSlash}
                      strict
                    />
                    <Route component={Login} path={PATH_LOGIN} />
                    <Route component={Logout} path={PATH_LOGOUT} />
                    <Redirect
                      exact
                      from={PATH_ORDER_ENTRY}
                      key={PATH_ORDER_ENTRY}
                      to={PATH_ORDERS}
                    />
                    <Redirect
                      exact
                      from={PATH_ORDER_ENTRY_ALT}
                      key={PATH_ORDER_ENTRY_ALT}
                      to={PATH_ORDERS}
                    />
                    <AuthRoute
                      component={Order}
                      isLoggedIn={isLoggedIn}
                      path={PATH_ORDER_ID}
                    />
                    <AuthRoute
                      component={Order}
                      isLoggedIn={isLoggedIn}
                      path={PATH_ORDER_ID_ALT}
                    />
```

Because you easily have a couple of layers in each component.

And regarding the notion of "subjective change" - yes almost everything is subjective regarding lint, let's not forget the "tabs vs spaces" and "semicolon" wars...

**Comment by Jiert** [comment]
👍

**Comment by tschaub** [comment]
Good to see you, @Jiert !

**Comment by andrewzey** [comment]
💪

**Comment by tschaub** [comment]
excited

**Comment by Primajin** [comment]
🤷🏻‍♂️

**Comment by tschaub** [comment]
Hi @Primajin. Good to see you too. In case it was confusing, my excitement gif above was about connecting with old friends (instead of about closing this issue).

**Pull request closed without merging**
