### PR TITLE
Enforce Trailing Commas on Multi-line

### PR DESCRIPTION
**Pull request by andrewzey**
## Changes
- enforces trailing comma on multi-line (but not on single-line) (http://eslint.org/docs/rules/comma-dangle)

Trailing commas simplify adding and removing items to objects and arrays, since only the lines you are modifying must be touched. Another argument in favor of trailing commas is that it improves the clarity of diffs when an item is added or removed from an object or array:

image

It also makes it easier to quickly re-arrange list items without having to manage commas (this comes up all the time , especially when dealing with `mapStateToProps`, `mapDispatchToProps`, `propTypes`.

image

### CODE REVIEW

**Comment by geuis** [comment]
I dunno. This is already allowed in the language spec. Why do we need a rule to enforce it? You don't always need trailing commas and its weird to force them.

**Comment by tschaub** [comment]
As with all other rules, the important part is consistency.  Fix on save removes the need to think about any of this.  I'm in favor.

**Comment by tschaub** [comment]
Please reopen if you fix conflicts (and can ensure this works with Prettier).

**Comment by andrewzey** [comment]
@tschaub Rebased, confirmed works with prettier, and re-opened: https://github.com/planetlabs/eslint-config-planet/pull/21

**Pull request closed without merging**
